(define timer
  (let* ((t 0) (n 10) (updater (new timer% [notify-callback (lambda ()
                                                              (when (= n 0)
                                                                (send updater stop))
                                                              (set! t (+ t 1))
                                                              (set! n (- n 1))
                                                              (display t))])))
    (lambda args 
      (cond ((null? args) t)
            ((eq? (car args) 'start)
             (send updater start 1000))
            ((eq? (car args) 'reset)
             (set! t 0)
                   (set! n 10)
                   (send updater stop))
            ((eq? (car args) 'stop)
             (send updater stop))
            (else (void))))))